"""add book inventory columns

Revision ID: 2890a066f3db
Revises: 
Create Date: 2026-03-14 18:56:55.848513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2890a066f3db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('total_books', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('available_books', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_deleted')
    op.drop_column('books', 'available_books')
    op.drop_column('books', 'total_books')
    # ### end Alembic commands ###
